### PR TITLE
Build out views

### PR DESCRIPTION
**Pull request by ironcoconut**
Just need to migrate and start the server. Everything should work.

make-user-admin
edit-shelter
shelter-table
proposed-changes

### CODE REVIEW

**Comment by ironcoconut** [comment]
Root now redirects to shelters table.
~~No tests. Not one. :(~~
Tests for all routes. The models aren't doing much. Might be nice to ensure the tables have the right data but meh?

**Comment by jwo** [comment]
Great job on the views @ironcoconut and @dorton .... First pass through the PR looks great. going to test locally.

**Comment by ironcoconut** [comment]
Add the first admin via console (after registering the user via the up) 

```
User.where(email: [email]).first.toggle(:admin).save
```

That admin can approve the others.

**Review by jwo — APPROVED** [review]
@ironcoconut @dorton way impressed.

**Pull request merged**
