### PR TITLE
Making Some Fields Required

### PR DESCRIPTION
**Pull request by rmoscowitz**
Also removing lat/long from forms (is this ok?).

Sorry @ironcoconut, this is another untested one. I'll set up a local environment if I do another PR, promise!

### CODE REVIEW

**Review by ironcoconut — COMMENTED** [review]
The issue with making them required is you can't update the rest of the form unless you have that data. I'm not confident that is the case for all updates. If we could make it required only for create, I would be fine with that.

Though if they are missing crucial info they should probably be archived.

@jwo thoughts?

**Comment by jwo** [comment]
I think this means you cannot update the lat/lngs at all, ever. I think that's not the right move right now until we fix #28 

@rmoscowitz I am OK with setting them as required fields but need you to confirm that existing fields where that data is not present, that you cannot update them without setting those values.

**Comment by rmoscowitz** [comment]
Ok, I'll leave the lat/longs alone. Also I'll go check for records missing my new required fields. Thanks for the feedback yall!

**Review by jwo — APPROVED** [review]
👍 thanks for the work @rmoscowitz !

**Pull request merged**
