### PR TITLE
Geo code form

### LINKED ISSUE #28: TODO Fix geocoding on models
We had an emergency fix here: https://github.com/sketch-city/harvey-api/pull/25

This issue serves to remind us that automatic geocoding is disable for the moment.

Ideally geocoding should occur automatically. Determine for models:

- If sufficient address information exists to geocode automatically and consistently.
- Enable geocoding where possible.

This may not be possible until we migrate the DB to a better schema.

### PR DESCRIPTION
**Pull request by jwo**
Building off of the super wicked sweet component in #89, I've committed to browser based geocoding for shelters and needs.

browser-geocoding

Steps to make this work for you:

1. Add a `GOOGLE_MAPS_JS_API_KEY` to your `.env`. The server side `GOOGLE_GEOCODER_API` didn't work for me.
2. smile and enjoy

When you show a shelter/need it shows you what the map is.

screen shot 2017-09-09 at 10 46 26 am

Additionally, this deletes the rake task from existence. Farewell.

Closes #28 
Closes #89
Ping #84

### CODE REVIEW

**Comment by jwo** [comment]
@ironcoconut this should be simplistic to integrate with the v2 dataset, but this pull does not attempt to do that.

**Review by ironcoconut — APPROVED** [review]
Awesome

**Comment by tdooner** [comment]
Aww, we just duplicated this work. https://github.com/Irma-Response/irma-api/commit/a8ef2cb36de5112d1e97e1330444205d4fd5d6a5. I think your implementation is a bit nicer because of the map/flexible field naming.

At some point we'll get everything combined back together.

**Comment by ironcoconut** [comment]
@tdooner does this mean you can't merge in our master?

**Pull request merged**
