### PR TITLE
Update with actioncable and system tests to test it

### PR DESCRIPTION
**Pull request by jwo**
update

### CODE REVIEW

**Comment by jwo** [comment]
(working on getting travis-ci to run chrome headless)

**Review by ironcoconut — DISMISSED** [review]
Looks good. I'll add the table update code once I get a second.

Feel free to merge once you figure the tests out.

**Comment by jwo** [comment]
@ironcoconut will you give your 👍 on a review?

**Review by ironcoconut — APPROVED** [review]

**Comment by ironcoconut** [comment]
@jwo you merge. I am not available to watch if anything goes terribly wrong. <- I don't think it will, just in case.

**Comment by jwo** [comment]
@ironcoconut on it!

**Pull request merged**
