### PR TITLE
DO NOT MERGE: will actually delete the import code

### PR DESCRIPTION
**Pull request by jwo**
Updates .env and README to not mention google permissions either, which are now not needed

### CODE REVIEW

**Comment by ironcoconut** [comment]
Might want to mention in the readme how to add an admin for testing.

**Review by ironcoconut — COMMENTED** [review]
We will need seed data so peeps can populate the DB.

**Comment by jwo** [comment]
> We will need seed data so peeps can populate the DB.

So I went about creating this and then wondered if it was a good idea or not to have lat/lng in git history repos.  It gave me pause.

What about something that will load from the api endpoints and create locally?

Anyone have thoughts on this approach?

**Comment by ironcoconut** [comment]
Sounds good. Easier than maintaining seed data. We will have to update when the schema changes, but we have to do that no matter what. 

Could be an issue if new people expect seed data but we can put it in the readme.

**Comment by cmason** [comment]
> What about something that will load from the api endpoints and create locally?

Wouldn't be easier/quicker to seed from the latest production db backup in that case?

**Comment by ironcoconut** [comment]
The API is public and downloading from it should be just as quick as restoring from a backup. I'm not opposed to using a backup but I don't have as quick an answer for how to provide a link to the backup for everyone. Whereas the public API is already public and well maintained.

**Comment by jwo** [comment]
Closing in favor of evaluating what code should live and die bespokely. 

#coderot

**Pull request closed without merging**
