### PR TITLE
Device uuids

### PR DESCRIPTION
**Pull request by cmason**
Adds device uuids to markers allowing clients to identify markers they have created.

Categories endpoint now includes an `icons` key that maps category keys to icon keys. This allows the icons in the app to be updated without resubmitting to the app store.

### CODE REVIEW

**Comment by jwo** [comment]
@cmason we were thinking of turning all pk's in uuids.... do you have opinions? We haven't propagated out any ids, ever.

@ironcoconut we talked about this, basically. thoughts from you?

**Comment by cmason** [comment]
I don't have any objections to that. Makes life much easier when it comes time to shard. It does mess up the default ordering, but an index on `:created_at` easily resolves that.  The bigger issue is that it breaks (at least it used to) batch processing because `find_each` expects the ids to be incremental.

**Comment by cmason** [comment]
BTW, the device uuid here is to identify individual devices without needing authentication. It still needs more work. Please don't merge yet.

**Comment by ironcoconut** [comment]
This looks ok to me. Uuids in this context make sense. Not sure about for all pks, though. I can't remember the arguments for and against.

**Review by jwo — APPROVED** [review]
👍

**Comment by jwo** [comment]
@cmason merged and going live on harvey-api soon

**Pull request merged**
